// Actions types definition
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_SINGLE_PERSON = 'FETCH_SINGLE_PERSON';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = "UNAUTH_USER";
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const FETCH_PERSONS_PAGES_INFO = 'FETCH_PERSONS_PAGES_INFO';
